### ISSUE TITLE
en_US.UTF-8

### ISSUE THREAD

**Issue by RichardPasmans** [moritzheiber/piwigo-docker#1]
Hi Mr Heiber,

Cloned git, used docker-compose up -d and go the following issue:

```
 ---> Running in 254397bedaf9
/bin/sh: 1: locale-gen: not found
ERROR: Service 'piwigo-fpm' failed to build: The command '/bin/sh -c locale-gen en_US.UTF-8' returned a non-zero code: 127
```

Is it due to this bug?
https://bugs.launchpad.net/ubuntu/+bug/920601

**Comment by moritzheiber** [comment]
I don’t think that’s the issue, but I’ll look into it shortly 😊

**Comment by moritzheiber** [comment]
I think this is solved with the latest update I just pushed. Could you please verify?

**Comment by moritzheiber** [comment]
I think this is solved, if it persists please open another issue.
